const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'chrome'});
const page=await browser.newPage({viewport:{width:1024,height:600}});
const points=Array.from({length:30},(_,i)=>({x:i*.1,y:1,yaw:0}));
const state={device_id:'QA',mode:'navigation',map:null,pose:null,navigation:{ready:true,planner_ready:true},localization:{ready:true,match:.98},mission:{state:'idle',points:[],index:0,mode:'multi'},lidar:{state:'online'},camera:{state:'offline'},metrics:{},streams:{rviz_state:'offline'},platform:{state:'unconfigured'},active_map_id:'test',speed_mps:.2,max_speed_mps:.35};
await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname; if(route.request().method()!=='GET')throw new Error('Unexpected POST '+path);const data=path.endsWith('/session')?{token:'test',can_control:true}:path.endsWith('/maps')?{maps:[{id:'test',name:'测试地图'}]}:path.endsWith('/routes')?{routes:[{id:'r',name:'30 个航点',map_id:'test',points,mode:'multi',speed_mps:.2}]}:{};return route.fulfill({json:data})});
await page.routeWebSocket('**/api/ws',ws=>{ws.send(JSON.stringify({type:'state',payload:state}));const t=setInterval(()=>ws.send(JSON.stringify({type:'state',payload:state})),500);t.unref();ws.onClose(()=>clearInterval(t))});
await page.goto('http://127.0.0.1:5178/?tab=cruise');
await page.getByLabel('选择已保存路线').selectOption('r');
await page.getByRole('button',{name:'编辑航点，共 30 个'}).click();
if(await page.getByLabel(/航点\d+ 朝向/).count())throw new Error('Heading editor must be absent');
await page.getByLabel('航点30 X',{exact:true}).fill('3.75');
await page.getByRole('button',{name:'上移航点30',exact:true}).click();
if(await page.getByLabel('航点29 X',{exact:true}).inputValue()!=='3.75')throw new Error('Reorder failed');
await page.getByRole('button',{name:'删除航点30',exact:true}).click();
const box=await page.locator('.waypoint-editor').boundingBox();if(box.y<0||box.y+box.height>600||box.width<800)throw new Error('Dialog size invalid');
await page.screenshot({path:'/tmp/waypoint-editor-1024.png'});
await page.getByRole('button',{name:'应用修改',exact:true}).click();
await page.getByRole('button',{name:'编辑航点，共 29 个'}).click();
if(await page.getByLabel('航点29 X',{exact:true}).inputValue()!=='3.75')throw new Error('Apply failed');
await page.getByLabel('航点1 X',{exact:true}).fill('');
if(await page.getByRole('button',{name:'应用修改',exact:true}).isEnabled())throw new Error('Invalid accepted');
await page.getByRole('button',{name:'取消',exact:true}).click();
await page.getByRole('button',{name:'编辑航点，共 29 个'}).click();
if(await page.getByLabel('航点1 X',{exact:true}).inputValue()==='')throw new Error('Cancel failed');
await page.setViewportSize({width:375,height:667});await page.screenshot({path:'/tmp/waypoint-editor-375.png'});
const small=await page.locator('.waypoint-editor').boundingBox();if(small.x<0||small.x+small.width>375)throw new Error('Narrow overflow');
await page.keyboard.press('Escape');if(await page.locator('dialog').count())throw new Error('Escape failed');
console.log('PASS: 30 waypoints, last-row edit, reorder, delete, apply/cancel, validation, Escape, 1024x600 and 375x667 layouts; no POST requests');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
